### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by carmenfdezb** [donaggio/harbour-feedhaven#1]
I would like to translate your app to Spanish language. Could you add translations?
Thanks for your app, it's an excellent feeds reader.

**Comment by donaggio** [comment]
I'll certainly do that, thanks for offering to help with translations!

**Comment by donaggio** [comment]
Added .ts files

**Comment by carmenfdezb** [comment]
Great!! I will translate to Spanish as soon as possible.
Thanks so much!!
