### ISSUE TITLE
Build for Jolla Tablet

### ISSUE THREAD

**Issue by carmenfdezb** [donaggio/harbour-feedhaven#3]
I would appreciate if you add build fro Jolla Tablet.
Thanks for the great app!

**Comment by carmenfdezb** [comment]
I've tried to build your app for Jolla tablet, but when I open the app it shows an error in log in page, could you help me?

**Comment by donaggio** [comment]
Sorry Carmen, I've not been active on this project, but lots of troubles in real life prevents me doing so.
To be able to build from source you'll need a secret Feedly API key which I've not included in the public GIT. I'll make an X86 build and mail it to you, it's not properly done for larger screen devices such as the tablet (and that's why I'm not pushing it to Jolla store yet), but at least it should work now.

**Comment by carmenfdezb** [comment]
Maybe it doesn't look perfect in Jolla Tablet, but it's an excellent app, thank you so much!!

If you want, I can send you screenshots, you can see how it looks in Jolla Tablet and so you can decide to public in Jolla Store.

**Comment by carmenfdezb** [comment]
Hi donaggio!
I hope everything in your life goes well, and I wish you the best in 2017.

I only wanted to put here screenshots of Feedhaven that I made from my tablet (I took databases from my phone to my tablet, and my build of Feedhaven works for a week in my tablet):

![captura_20170115_002](https://cloud.githubusercontent.com/assets/6286776/21962796/96476c00-db2e-11e6-9850-185f077b8341.png)

![captura_20170115_001](https://cloud.githubusercontent.com/assets/6286776/21962801/acd61480-db2e-11e6-8023-3b63fb00d937.png)

![captura_20170115_003](https://cloud.githubusercontent.com/assets/6286776/21962806/c933f3fe-db2e-11e6-98d4-89903edb05a4.png)

In my opinion, Feedhaven looks perfect in a tablet, so you could public x86 build in Jolla Store if you want.

Thanks for your attention.

**Comment by donaggio** [comment]
Thank you Carmen!
I've just submitted to Harbour the latest version also as an x86 package for Jolla Tablet.

**Comment by carmenfdezb** [comment]
Thank you so much!!!
